[project]
name = "cnme"
version = "0.1.0"
description = "Deep kernel tests for interventional distributions"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.3",
    "scikit-learn>=1.8.0",
    "torchvision>=0.25.0",
    "h5py>=3.16.0",
    "gdown>=5.2.1",
    "pandas>=3.0.2",
    "medmnist>=3.0.2",
    "transformers>=5.12.1",
    "sentence-transformers>=5.6.0",
    "tqdm>=4.68.3",
    "kagglehub>=1.0.2",
    "datasets>=3.0.0",
    "networkx>=3.6.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
]

[tool.ruff]
line-length = 10000

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP"]
